-- Your SQL goes here
CREATE TABLE chatters (
   id SERIAL PRIMARY KEY,
   username VARCHAR NOT NULL,
   points INTEGER NOT NULL DEFAULT 0,
   wins INTEGER NOT NULL DEFAULT 0,
   losses INTEGER NOT NULL DEFAULT 0
)