services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  default:
    driver: bridge
