-- Your SQL goes here
ALTER TABLE duels
ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'challenged';

ALTER TABLE duels
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE duels
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
